[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.2.0"
pic8259 = "0.11.0"
spin = "0.9.8"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.x86_64]
version = "0.15.1"
features = ["instructions"]
